export const textStyles = {
  '.mobile-extra-large': {
    fontFamily: 'Noto_Sans_KR',
    fontSize: '26px',
    lineHeight: '38px',
    fontWeight: '400',
    textDecoration: 'none',
    letterSpacing: '0',
  },
  '.mobile-title-large': {
    fontFamily: 'Noto_Sans_KR',
    fontSize: '20px',
    lineHeight: '29px',
    fontWeight: '700',
    textDecoration: 'none',
    letterSpacing: '0',
  },
  '.mobile-title': {
    fontFamily: 'Noto_Sans_KR',
    fontSize: '16px',
    lineHeight: '28px',
    fontWeight: '700',
    textDecoration: 'none',
    letterSpacing: '0',
  },
  '.mobile-title-small': {
    fontFamily: 'Noto_Sans_KR',
    fontSize: '12px',
    lineHeight: '18px',
    fontWeight: '700',
    textDecoration: 'none',
    letterSpacing: '0',
  },
  '.mobile-text-large': {
    fontFamily: 'Noto_Sans_KR',
    fontSize: '20px',
    lineHeight: '29px',
    fontWeight: '400',
    textDecoration: 'none',
    letterSpacing: '0',
  },
  '.mobile-text': {
    fontFamily: 'Noto_Sans_KR',
    fontSize: '16px',
    lineHeight: '28px',
    fontWeight: '400',
    textDecoration: 'none',
    letterSpacing: '0',
  },
  '.mobile-text-small': {
    fontFamily: 'Noto_Sans_KR',
    fontSize: '12px',
    lineHeight: '18px',
    fontWeight: '400',
    textDecoration: 'none',
    letterSpacing: '0',
  },
  '.mobile-button': {
    fontFamily: 'Noto_Sans_KR',
    fontSize: '16px',
    lineHeight: '28px',
    fontWeight: '700',
    textDecoration: 'none',
    letterSpacing: '0',
  },
  '.mobile-button-small': {
    fontFamily: 'Noto_Sans_KR',
    fontSize: '12px',
    lineHeight: '18px',
    fontWeight: '700',
    textDecoration: 'none',
    letterSpacing: '0',
  },
  '.mobile-text-active': {
    fontFamily: 'Noto_Sans_KR',
    fontSize: '16px',
    lineHeight: '28px',
    fontWeight: '400',
    textDecoration: 'underline',
    letterSpacing: '0',
  },
  '.mobile-text-small-active': {
    fontFamily: 'Noto_Sans_KR',
    fontSize: '12px',
    lineHeight: '18px',
    fontWeight: '400',
    textDecoration: 'underline',
    letterSpacing: '0',
  },
};
